# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57d4652abb50b946a79ba2424810b75b0c2e7b59770c928258369b2cfd3462e197aa0a9d9f28ae815d3d2db294905de409cc154cf62234e6ffaae85748f3ce90

test:
  secret_key_base: 99982ca588ec88c4f25e878d80ececa5c48f15c45b3ca127f51f0733a5390a983b3f6aaa283aae195273b48f5d656d2f39d1a0ff6c2f207441ebbe52ffdccfc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
